In [1]:
import numpy as np

In [2]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

In [3]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[5, 2, 6, 6],
         [8, 7, 8, 5],
         [8, 6, 9, 3]],
 
        [[2, 5, 3, 6],
         [8, 9, 4, 2],
         [6, 4, 2, 1]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [4]:
## Arithmetic in arrays is element wise

In [5]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [6]:
c = a-b
c

array([20, 29, 38, 47])

In [7]:
b**2

array([0, 1, 4, 9])

In [8]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [9]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
a[2:5]

array([ 4,  9, 16])

In [11]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [12]:
b = np.random.randint(1,100,(4,4))

In [13]:
b

array([[76, 18, 63, 19],
       [66, 76, 36, 36],
       [77, 54, 80, 45],
       [72, 36,  7, 67]])

In [17]:
# Guess the output
print(b[2,3])
print(b[0,0])

45
76


In [18]:
b[0:3,1],b[:,1]

(array([18, 76, 54]), array([18, 76, 54, 36]))

In [19]:
b[1:3,:]

array([[66, 76, 36, 36],
       [77, 54, 80, 45]])

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [22]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [23]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  0.446105 -0.082390  1.383175  1.235848
2014-01-02  1.380626  0.983796  0.841653 -0.691361
2014-01-03 -2.036512 -0.612769  0.244205  0.121230
2014-01-04 -1.918239 -0.786577  2.109568  0.529927
2014-01-05  0.762545 -0.879686  0.616104 -0.523969
2014-01-06  0.622504  0.260750  0.382190  0.488227

In [24]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [25]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

In [26]:
df.head()

A         B         C         D
2014-01-01  0.446105 -0.082390  1.383175  1.235848
2014-01-02  1.380626  0.983796  0.841653 -0.691361
2014-01-03 -2.036512 -0.612769  0.244205  0.121230
2014-01-04 -1.918239 -0.786577  2.109568  0.529927
2014-01-05  0.762545 -0.879686  0.616104 -0.523969

In [27]:
df.tail()

A         B         C         D
2014-01-02  1.380626  0.983796  0.841653 -0.691361
2014-01-03 -2.036512 -0.612769  0.244205  0.121230
2014-01-04 -1.918239 -0.786577  2.109568  0.529927
2014-01-05  0.762545 -0.879686  0.616104 -0.523969
2014-01-06  0.622504  0.260750  0.382190  0.488227

In [28]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [29]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.123829 -0.186146  0.929482  0.193317
std    1.470316  0.721494  0.703348  0.719652
min   -2.036512 -0.879686  0.244205 -0.691361
25%   -1.327153 -0.743125  0.440668 -0.362669
50%    0.534305 -0.347580  0.728878  0.304728
75%    0.727535  0.174965  1.247794  0.519502
max    1.380626  0.983796  2.109568  1.235848

In [30]:
df.sort_values(by='B')
df

A         B         C         D
2014-01-01  0.446105 -0.082390  1.383175  1.235848
2014-01-02  1.380626  0.983796  0.841653 -0.691361
2014-01-03 -2.036512 -0.612769  0.244205  0.121230
2014-01-04 -1.918239 -0.786577  2.109568  0.529927
2014-01-05  0.762545 -0.879686  0.616104 -0.523969
2014-01-06  0.622504  0.260750  0.382190  0.488227

In [31]:
df[['A','B']]

A         B
2014-01-01  0.446105 -0.082390
2014-01-02  1.380626  0.983796
2014-01-03 -2.036512 -0.612769
2014-01-04 -1.918239 -0.786577
2014-01-05  0.762545 -0.879686
2014-01-06  0.622504  0.260750

In [32]:
df[0:3]

A         B         C         D
2014-01-01  0.446105 -0.082390  1.383175  1.235848
2014-01-02  1.380626  0.983796  0.841653 -0.691361
2014-01-03 -2.036512 -0.612769  0.244205  0.121230

In [33]:
# By label
df.loc[dates[0]]

A    0.446105
B   -0.082390
C    1.383175
D    1.235848
Name: 2014-01-01 00:00:00, dtype: float64

In [34]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  0.446105 -0.082390
2014-01-02  1.380626  0.983796
2014-01-03 -2.036512 -0.612769
2014-01-04 -1.918239 -0.786577
2014-01-05  0.762545 -0.879686
2014-01-06  0.622504  0.260750

In [35]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  0.983796
2014-01-03 -0.612769
2014-01-04 -0.786577

In [36]:
# Fast access to scalar
df.at[dates[1],'B']

0.98379622599856087

In [37]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04 -1.918239 -0.786577  2.109568  0.529927
2014-01-05  0.762545 -0.879686  0.616104 -0.523969
2014-01-06  0.622504  0.260750  0.382190  0.488227

In [38]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-03 -2.036512 -0.612769  0.244205  0.121230
2014-01-04 -1.918239 -0.786577  2.109568  0.529927

In [39]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [40]:
df_posA

A         B         C         D
2014-01-01  0.446105 -0.082390  1.383175  1.235848
2014-01-02  1.380626  0.983796  0.841653 -0.691361
2014-01-03  2.036512  0.612769 -0.244205 -0.121230
2014-01-04  1.918239  0.786577 -2.109568 -0.529927
2014-01-05  0.762545 -0.879686  0.616104 -0.523969
2014-01-06  0.622504  0.260750  0.382190  0.488227

In [41]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [42]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [43]:
df['F'] = s1

In [44]:
df

A         B         C         D    F
2014-01-01  0.446105 -0.082390  1.383175  1.235848  NaN
2014-01-02  1.380626  0.983796  0.841653 -0.691361  1.0
2014-01-03 -2.036512 -0.612769  0.244205  0.121230  2.0
2014-01-04 -1.918239 -0.786577  2.109568  0.529927  3.0
2014-01-05  0.762545 -0.879686  0.616104 -0.523969  4.0
2014-01-06  0.622504  0.260750  0.382190  0.488227  5.0

In [45]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [46]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [47]:
df1

A         B         C         D    F    E
2014-01-01  0.446105 -0.082390  1.383175  1.235848  NaN  1.0
2014-01-02  1.380626  0.983796  0.841653 -0.691361  1.0  1.0
2014-01-03 -2.036512 -0.612769  0.244205  0.121230  2.0  NaN
2014-01-04 -1.918239 -0.786577  2.109568  0.529927  3.0  NaN

In [48]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

In [49]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.123829 -0.186146  0.929482  0.193317  3.000000
std    1.470316  0.721494  0.703348  0.719652  1.581139
min   -2.036512 -0.879686  0.244205 -0.691361  1.000000
25%   -1.327153 -0.743125  0.440668 -0.362669  2.000000
50%    0.534305 -0.347580  0.728878  0.304728  3.000000
75%    0.727535  0.174965  1.247794  0.519502  4.000000
max    1.380626  0.983796  2.109568  1.235848  5.000000

In [50]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.123829
 B   -0.186146
 C    0.929482
 D    0.193317
 F    3.000000
 dtype: float64, 2014-01-01    0.745684
 2014-01-02    0.702943
 2014-01-03   -0.056769
 2014-01-04    0.586936
 2014-01-05    0.794999
 2014-01-06    1.350734
 Freq: D, dtype: float64)

In [51]:
df

A         B         C         D    F
2014-01-01  0.446105 -0.082390  1.383175  1.235848  NaN
2014-01-02  1.380626  0.983796  0.841653 -0.691361  1.0
2014-01-03 -2.036512 -0.612769  0.244205  0.121230  2.0
2014-01-04 -1.918239 -0.786577  2.109568  0.529927  3.0
2014-01-05  0.762545 -0.879686  0.616104 -0.523969  4.0
2014-01-06  0.622504  0.260750  0.382190  0.488227  5.0

In [52]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  0.446105 -0.082390  1.383175  1.235848   NaN
2014-01-02  1.826731  0.901406  2.224827  0.544487   1.0
2014-01-03 -0.209781  0.288637  2.469032  0.665717   3.0
2014-01-04 -2.128020 -0.497940  4.578600  1.195644   6.0
2014-01-05 -1.365475 -1.377625  5.194704  0.671675  10.0
2014-01-06 -0.742971 -1.116876  5.576894  1.159902  15.0

In [53]:
df.apply(lambda x: x.max() - x.min())

A    3.417138
B    1.863482
C    1.865363
D    1.927208
F    4.000000
dtype: float64

In [54]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [55]:
np.random.randn(10,4)

array([[ 0.98221565, -0.15739041,  2.63848892, -0.60068982],
       [-2.36050936,  0.70519844, -0.15396649, -0.33097752],
       [ 0.39012116, -1.13766887,  1.12383843,  1.41432778],
       [ 0.7863829 , -0.35332912, -0.49967548,  0.35973249],
       [ 2.37058846, -1.38231904,  1.85060896,  0.36815636],
       [ 1.07688697,  1.12036595, -1.06725128, -0.227009  ],
       [ 0.7761993 , -0.03928848,  0.73772289,  0.16347765],
       [-0.61773495,  0.33645658, -0.90589583,  0.45853716],
       [ 0.10398077, -0.06305325,  0.60030611,  0.55490625],
       [-0.27085427,  0.07679703, -0.31575467,  0.53600976]])

In [56]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -1.407023  0.869032  0.025283  1.047272
1 -0.100018  1.947626  0.037050  0.167512
2  1.179358  0.287644 -0.951534  1.127062
3 -0.940557 -0.728244  1.854306  0.903925
4 -2.059532  0.346408 -0.257612  0.947118
5 -0.397356 -1.878329  0.916838 -1.049146
6 -2.781764 -1.922038  0.670559 -3.332991
7 -0.076640  0.178754  0.637696 -1.604056
8  0.647178  1.336048 -0.154603  0.597191
9  0.643499  2.328243  0.086039 -0.432726

In [57]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -1.407023  0.869032  0.025283  1.047272
 1 -0.100018  1.947626  0.037050  0.167512
 2  1.179358  0.287644 -0.951534  1.127062,
           0         1         2         3
 3 -0.940557 -0.728244  1.854306  0.903925
 4 -2.059532  0.346408 -0.257612  0.947118
 5 -0.397356 -1.878329  0.916838 -1.049146
 6 -2.781764 -1.922038  0.670559 -3.332991,
           0         1         2         3
 7 -0.076640  0.178754  0.637696 -1.604056
 8  0.647178  1.336048 -0.154603  0.597191
 9  0.643499  2.328243  0.086039 -0.432726]

In [58]:
pd.concat(pieces)

0         1         2         3
0 -1.407023  0.869032  0.025283  1.047272
1 -0.100018  1.947626  0.037050  0.167512
2  1.179358  0.287644 -0.951534  1.127062
3 -0.940557 -0.728244  1.854306  0.903925
4 -2.059532  0.346408 -0.257612  0.947118
5 -0.397356 -1.878329  0.916838 -1.049146
6 -2.781764 -1.922038  0.670559 -3.332991
7 -0.076640  0.178754  0.637696 -1.604056
8  0.647178  1.336048 -0.154603  0.597191
9  0.643499  2.328243  0.086039 -0.432726

In [59]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -1.407023  0.869032  0.025283  1.047272
1 -0.100018  1.947626  0.037050  0.167512
2  1.179358  0.287644 -0.951534  1.127062
3 -0.940557 -0.728244  1.854306  0.903925
4 -2.059532  0.346408 -0.257612  0.947118
5 -0.397356 -1.878329  0.916838 -1.049146
6 -2.781764 -1.922038  0.670559 -3.332991
7 -0.076640  0.178754  0.637696 -1.604056
8  0.647178  1.336048 -0.154603  0.597191
9  0.643499  2.328243  0.086039 -0.432726

In [60]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [61]:
df

A      B         C         D
0  foo    one -1.016629  0.905053
1  bar    one -1.083802  2.110321
2  foo    two -0.249424 -1.537936
3  bar  three  0.401273  0.665456
4  foo    two -0.525455 -0.339486
5  bar    two -0.375993  0.162382
6  foo    one  0.901617 -0.303875
7  foo  three -0.099543  1.841533

In [62]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -1.083802  2.110321
    three  0.401273  0.665456
    two   -0.375993  0.162382
foo one   -0.115012  0.601178
    three -0.099543  1.841533
    two   -0.774880 -1.877422

In [63]:
# You can also stack or unstack levels

In [64]:
a = df.groupby(['A','B']).sum()

In [65]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -1.083802  0.401273 -0.375993  2.110321  0.665456  0.162382
foo -0.057506 -0.099543 -0.387440  0.300589  1.841533 -0.938711

In [66]:
import pandas as pd
import numpy as np

In [67]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [68]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [69]:
ts

2014-01-01 00:00:00     23
2014-01-01 00:00:01    426
2014-01-01 00:00:02    110
2014-01-01 00:00:03    485
2014-01-01 00:00:04    218
2014-01-01 00:00:05    419
2014-01-01 00:00:06    105
2014-01-01 00:00:07    343
2014-01-01 00:00:08    280
2014-01-01 00:00:09    316
2014-01-01 00:00:10    230
2014-01-01 00:00:11      0
2014-01-01 00:00:12    441
2014-01-01 00:00:13     81
2014-01-01 00:00:14     72
2014-01-01 00:00:15    127
2014-01-01 00:00:16    153
2014-01-01 00:00:17    273
2014-01-01 00:00:18     28
2014-01-01 00:00:19    408
2014-01-01 00:00:20    432
2014-01-01 00:00:21    417
2014-01-01 00:00:22    205
2014-01-01 00:00:23    468
2014-01-01 00:00:24     17
2014-01-01 00:00:25    271
2014-01-01 00:00:26    498
2014-01-01 00:00:27    449
2014-01-01 00:00:28    367
2014-01-01 00:00:29     60
                      ... 
2014-01-01 00:01:10    227
2014-01-01 00:01:11    242
2014-01-01 00:01:12    244
2014-01-01 00:01:13    331
2014-01-01 00:01:14    396
2014-01-01 00:01:15    232
2

In [70]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    249.816667
2014-01-01 00:01:00    238.750000
Freq: T, dtype: float64

In [71]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-71-5c9240a56f62>, line 2)

In [72]:
ts

2014-01-01 00:00:00     23
2014-01-01 00:00:01    426
2014-01-01 00:00:02    110
2014-01-01 00:00:03    485
2014-01-01 00:00:04    218
2014-01-01 00:00:05    419
2014-01-01 00:00:06    105
2014-01-01 00:00:07    343
2014-01-01 00:00:08    280
2014-01-01 00:00:09    316
2014-01-01 00:00:10    230
2014-01-01 00:00:11      0
2014-01-01 00:00:12    441
2014-01-01 00:00:13     81
2014-01-01 00:00:14     72
2014-01-01 00:00:15    127
2014-01-01 00:00:16    153
2014-01-01 00:00:17    273
2014-01-01 00:00:18     28
2014-01-01 00:00:19    408
2014-01-01 00:00:20    432
2014-01-01 00:00:21    417
2014-01-01 00:00:22    205
2014-01-01 00:00:23    468
2014-01-01 00:00:24     17
2014-01-01 00:00:25    271
2014-01-01 00:00:26    498
2014-01-01 00:00:27    449
2014-01-01 00:00:28    367
2014-01-01 00:00:29     60
                      ... 
2014-01-01 00:01:10    227
2014-01-01 00:01:11    242
2014-01-01 00:01:12    244
2014-01-01 00:01:13    331
2014-01-01 00:01:14    396
2014-01-01 00:01:15    232
2

In [73]:
ts.plot()

In [74]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [75]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [76]:
# Pandas plot function will print with labels as default

In [77]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #